mybatis:
  type-aliases-package: com.cn.springcloud.entity
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  port: 8003
spring:
  application:
    name: MICROSERVICECLOUD-DEPT
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDBo3?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-provider-dept-8003 #修改显示的服务名
    prefer-ip-address: true #显示访问路劲ip地址

info:
  app.name: microservicecloud-provider-dept-8001
  company.name: www.cmdhfusd.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$